### ISSUE TITLE
Style improvements

### ISSUE THREAD

**Issue by brianmhunt** [mikeal/r2#21]
Much like #10, consider some ES6ish things:

1. The `defineProperty` code is unnecessarily verbose. Consider
  i. changing the `defineProperty` to getters e.g. `get json () { return this.response.then(resp => resp.clone().json()) }` or
  ii. using `['json', 'blob', ...].forEach((n) => Object.defineProperty(this, n, {get: () => this.response.then(r => r.clone()[n]()})` or
  iii. using `defineProperties` 
2. Define `setHeaders(obj = {})` and remove `if (opts.headers)`
3. change `makeBody` to a named function so that its name shows up when debugging
4. change `setHeader (key, value) { this.setHeaders({ [key]: value }) }`
5. have `_args` return `this`, then change all the http method methods (`get`, `post`, ...) to `return this._args(...args)`

**Comment by gr2m** [comment]
### done via #38
- [x] The `defineProperty` code is unnecessarily verbose. Consider
  i. changing the `defineProperty` to getters e.g. `get json () { return this.response.then(resp => resp.clone().json()) }` or
  ii. using `['json', 'blob', ...].forEach((n) => Object.defineProperty(this, n, {get: () => this.response.then(r => r.clone()[n]()})` or
  iii. using `defineProperties` 

### PR at  #56
- [x] change `makeBody` to a named function so that its name shows up when debugging
- [x] change `setHeader (key, value) { this.setHeaders({ [key]: value }) }`
- [x] Define `setHeaders(obj = {})` and remove `if (opts.headers)`

### I think that’s obsolete

- [ ] have `_args` return `this`, then change all the http method methods (`get`, `post`, ...) to `return this._args(...args)`

**Comment by brianmhunt** [comment]
I find this oddly satisfying. 😉
